#!/usr/bin/env bash

D="$(dirname "$0")"
F="$D/requirements.txt"

echo "# This file was generated by $(basename "$0")" > "$F"
echo >> "$F"

bash "$D/pkg/generate-requirements.sh" "$@" | tee -a "$F"

CMD=( pip install --upgrade -r requirements.txt )

read -ep "issue ${CMD[*]}? [Y/n]" YN
[[ "$YN" =~ [Nn] ]] || "${CMD[@]}"
